title: Maimonides' Guide for the Perplexed
author: Â© Emad Masroor  

description: >- # this means to ignore newlines until "baseurl:"
  A personal summary of and commentary on 
  Maimonides' Guide for the Perplexed
baseurl: "/Guide-Perplexed" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
email: emadmasroor@gmail.com

# Build settings
theme: minima
# plugins:
#  - jekyll-feed

markdown: kramdown

collections:
  GPI_chapters:
    output: true
    permalink: /summaries/I/:path/
    sort_by: chapter
  GPII_chapters:
    output: true
    permalink: /summaries/II/:path/
    sort_by: chapter
  GPIII_chapters:
    output: true
    permalink: /summaries/III/:path/
    sort_by: chapter
  Resources:
    output: true
    permalink: /resources/:path/
    
    

# the above line (output:true) ensures that each chapter has its own page

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Table of contents
plugins:
  - jemoji
#  - jekyll-toc
